server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123123
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    h2:
      console:
        path: /h2-console
        settings:
          trace: true
          web-allow-others: true
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak-idp:
            authorization-grant-type: authorization_code
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:pkce-authz-demo}
            #client-secret: ${KEYCLOAK_CLIENT_SECRET:45c090b2-e947-4f67-b918-53e325dc574c}
            scope: openid
            client-name: Sign in with Keycloak
        provider:
          keycloak:
            authorization-uri: https://tigahealth-keycloak-prod.pharmatick.com/auth/realms/tiga-health/protocol/openid-connect/auth
            token-uri: https://tigahealth-keycloak-prod.pharmatick.com/auth/realms/tiga-health/protocol/openid-connect/token
            user-info-uri: https://tigahealth-keycloak-prod.pharmatick.com/auth/realms/tiga-health/protocol/openid-connect/userinfo
            jwk-set-uri: https://tigahealth-keycloak-prod.pharmatick.com/auth/realms/tiga-health/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            issuer-uri: https://tigahealth-keycloak-prod.pharmatick.com/auth/realms/tiga-health

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.security.authorization: WARN
    org.springframework.security.authentication: WARN